/**
 * OpenAPI 3.0 Pet StoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Address {
  street?: string;
  city?: string;
  state?: string;
  zip?: string;
  additionalProperties?: Record<string, unknown>;
}

export const addressSchema: Schema<Address> = typedExpandoObject(
  {
    street: ['street', optional(string())],
    city: ['city', optional(string())],
    state: ['state', optional(string())],
    zip: ['zip', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
