/**
 * OpenAPI 3.0 Pet StoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address, addressSchema } from './address.js';

export interface Customer {
  id?: bigint;
  username?: string;
  address?: Address[];
  additionalProperties?: Record<string, unknown>;
}

export const customerSchema: Schema<Customer> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', optional(bigint())],
      username: ['username', optional(string())],
      address: [
        'address',
        optional(array(addressSchema, { xmlItemName: 'address' })),
        { xmlName: 'addresses' },
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
