/**
 * OpenAPI 3.0 Pet StoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status
 */
export enum Status {
  Placed = 'placed',
  Approved = 'approved',
  Delivered = 'delivered',
}

/**
 * Schema for Status
 */
export const statusSchema: Schema<Status> = stringEnum(Status);
