/**
 * OpenAPI 3.0 Pet StoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status2
 */
export enum Status2 {
  Available = 'available',
  Pending = 'pending',
  Sold = 'sold',
}

/**
 * Schema for Status2
 */
export const status2Schema: Schema<Status2> = stringEnum(Status2);
